# Generated by Django 4.1.10 on 2023-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edata',
            name='intensity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='edata',
            name='likelihood',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='edata',
            name='relevance',
            field=models.CharField(default='', max_length=100),
        ),
    ]
